[build]
    publish = "dist"
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "dist"
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
