---
- name: Aggiungi un nuovo utente
  hosts: all
  become: yes
  
  vars:
    username: ktor
    password: 
  
  tasks:
    - name: Creazione dell'utente
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        createhome: yes
        shell: /bin/bash
